## The model specification

The time needed to complete the current "task" at period t.

$$ D_t = B(1-pu_t) $$


Usefulness of most recent plan at time t


$$ u_{t+1} = r u_t $$
$$ u_1 = 1 $$
and u_t is reset back to 1 when a new plan is created. Thus

$$ u_{\sigma+1}=1, u_{2\sigma+1}=1, ... $$




The amount of time needed to create a plan for a given scope (sigma). If the scope is 5, then the plan would apply for 5 periods, including the period it was created on.

$$ L = c \sigma + k $$


## Table of Params

| Name            | Value | Description                                                                 |
|-----------------|-------|-----------------------------------------------------------------------------|
| SIM_PERIODS     | 25    | Total simulation periods (15 weeks of actual work, like Bren GP timeline).  |
| PLAN_DECAY_RATE | 0.9   | Rate at which plan usefulness decays (symbol: r). Use 0.9, 0.95, or 0.85.   |
| PLAN_SCOPE      | 25    | Intended duration of the plan in weeks (symbol: σ).                        |
| C               | 14.4  | Person-hours per week for plan drafting.                                   |
| K               | 40    | Baseline overhead for plan drafting in person-hours.                      |
| B               | 40    | Baseline time demand for one week's work in person-hours.                 |
| P               | 0.5   | Max reduction in time demand via perfect plan (20%). Use 0.75 or 0.25.    |
| SD_R            | 0.2   | Std. deviation for stochastic modeling of PLAN_DECAY_RATE.                |
| SD_C            | 5     | Std. deviation for stochastic modeling of C.                              |
| SD_K            | 10    | Std. deviation for stochastic modeling of K.                              |
| SD_B            | 10    | Std. deviation for stochastic modeling of B.                              |
| SD_P            | 0.2   | Std. deviation for stochastic modeling of P.                              |

## Values to test with

| Name            | Values                   |
|-----------------|--------------------------|
| SIM_PERIODS     | 25                       |
| PLAN_DECAY_RATE | 0.85, 0.9, 0.95          |
| PLAN_SCOPE      | 1, 2, 5, 25              |
| C               | 1, 5, 10, 15             |
| K               | 0, 1, 5, 10              |
| B               | 40                       |
| P               | 0.25, 0.5, 0.75          |
| SD_R            | 0.1, 0.2, 0.3            |
| SD_C            | 1, 5, 10, 15             |
| SD_K            | 1, 5, 10                 |
| SD_B            | 1, 5, 10                 |
| SD_P            | 0.1, 0.2, 0.3            |
