---
title: "Stochastic Model Calls"
author: "Ryan Anderson"
output:
  html_document:
    toc: true          # Enable table of contents
    toc_depth: 3       # Specify the depth of the TOC (e.g., 3 levels)
    toc_float: true    # Make the table of contents float (optional)
    code_folding: hide # Enable code folding (options: 'show' or 'hide')
---

Here we're gonna test stochastic model calls, we're gonna run them a bunch of times and extract key metrics.

## Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```


```{r}
# Clean env
rm(list = ls())

# Load libs
library(tidyverse)
library(here)
library(knitr)
library(kableExtra)

```



```{r}

# call source() for scripts/model.R
source(here("Final Project", "scripts", "model.R"))

```


# Parameters

So we're going to use some more realistic estimates for parameters here

```{r}

# Constants to Test With
SIM_PERIODS <- c(25) # 15 weeks of actual work (like Bren GP timeline we begin working over 2.5 quarters)

PLAN_DECAY_RATE <- c(0.85, 0.9, 0.95)
PLAN_SCOPE <- c(1, 2, 5, 25) 

C <- c(1, 5, 10, 15) # one person-hour per week of plan drafting. 
K <- c(0, 1, 5, 10) # one person-hour baseline of overhead for plan drafting

B <- c(40) # Baseline time demand for a week's worth of work on the project is 40 person hours
P <- c(0.25, 0.5, 0.75) # You can reduce the time demand by 20% at most by having a perfectly applicable plan. Can try 0.75 and 0.25 in sensitivity analysis.

# Let's also define some SD values for the error used in stochastic model
SD_R <- c(0.1, 0.2, 0.3)
SD_C <- c(1, 5, 10, 15)
SD_K <- c(1, 5, 10)
SD_B <- c(1, 5, 10)
SD_P <- c(0.1, 0.2, 0.3)
# Stick to single values
# SD_R <- c(0.2)
# SD_C <- c(5)
# SD_K <- c(10)
# SD_B <- c(10)
# SD_P <- c(0.2)




```

## Running the Model for all the param vals

```{r}

# Create a dataframe that consists of every single combination of the parameters
# Each column should have an appropriate name
combinations_df <- expand.grid(
  SIM_PERIODS = SIM_PERIODS,
  PLAN_DECAY_RATE = PLAN_DECAY_RATE,
  PLAN_SCOPE = PLAN_SCOPE,
  C = C,
  K = K,
  B = B,
  P = P,
  SD_R = SD_R,
  SD_C = SD_C,
  SD_K = SD_K,
  SD_B = SD_B,
  SD_P = SD_P
)

```

```{r}
# Run the model for each combination of parameters
# using run_stochastic_repetitions() helper func and add the summarized results to do the df
# results_df <- combinations_df %>% 
#   pmap_dfr(function(SIM_PERIODS, PLAN_DECAY_RATE, PLAN_SCOPE, C, K, B, P, SD_R, SD_C, SD_K, SD_B, SD_P) {
#     results_list <- run_stochastic_repetitions(1, SIM_PERIODS, PLAN_DECAY_RATE, PLAN_SCOPE, C, K, B, P, SD_R, SD_C, SD_K, SD_B, SD_P)
#     results_summary <- results_list$results_summary
#     results_summary %>% mutate(SIM_PERIODS = SIM_PERIODS, PLAN_DECAY_RATE = PLAN_DECAY_RATE, PLAN_SCOPE = PLAN_SCOPE, C = C, K = K, B = B, P = P, SD_R = SD_R, SD_C = SD_C, SD_K = SD_K, SD_B = SD_B, SD_P = SD_P)
#   })

# Accomplish using a for-loop
# define new empty fields in combinations_df
combinations_df$total_time_consumption <- NA
for (i in 1:nrow(combinations_df)) {
  results_list <- run_stochastic_repetitions(1, combinations_df$SIM_PERIODS[i],
                                             combinations_df$PLAN_DECAY_RATE[i],
                                             combinations_df$PLAN_SCOPE[i], 
                                             combinations_df$C[i], 
                                             combinations_df$K[i], combinations_df$B[i], combinations_df$P[i], combinations_df$SD_R[i], combinations_df$SD_C[i], combinations_df$SD_K[i], combinations_df$SD_B[i], combinations_df$SD_P[i])
  combinations_df$total_time_consumption[i] <- results_list$results_summary$mean_total_time_consumption
}


```

```{r}
# Using the combinations df, let's look at the distribution of each result by the plan_scope.
# make a histogram for each value of plan_scope
combinations_df %>% 
  ggplot(aes(x = total_time_consumption, fill = factor(PLAN_SCOPE))) +
  geom_histogram(position = "dodge", bins = 30) +
  labs(title = "Distribution of Total Time Consumption by Plan Scope",
       x = "Total Time Consumption",
       y = "Frequency") +
  theme_minimal()

# Do again but make the histograms seperate from each other
combinations_df %>% 
  ggplot(aes(x = total_time_consumption, fill = factor(PLAN_SCOPE))) +
  geom_histogram(position = "dodge", bins = 30) +
  facet_wrap(~PLAN_SCOPE) +
  labs(title = "Distribution of Total Time Consumption by Plan Scope",
       x = "Total Time Consumption (Person Hours)",
       y = "Frequency") +
  theme_minimal()

```

```{r}
# Save the 
```

```{r}
# Sawe the combinations df file to disk
write_csv(combinations_df, here("Final Project", "data", "combinations_df.csv"))
```

```{r}
```

```{r}
```

